### ISSUE TITLE
error is undefined..

### ISSUE THREAD

**Issue by Seungsoon** [squidit/instagram-node-api#8]
InstagramError

error is undefined.. throw exception

Sometimes there is not a declaration.

**Comment by Seungsoon** [comment]
oh... old version npmjs.com

**Comment by limafelipe** [comment]
Hi @Seungsoon 

Have you more information about when the error is throwing?

**Comment by Seungsoon** [comment]
Hi.

There is an error when the network is disconnected.

InstagramNodeApi.js
```
.catch((error) => {
  this.emit('err', new InstagramError(get(error, 'response.body')))
})
```

404 response error...?

may be 'response.body' is not exist..

InstagramError.js
```
InstagramError
class InstagramError extends Error {
  constructor (error) {
      super(error.meta.error_message) // error undefined? throw exception..
      this.type = error.meta.error_type
      this.statusCode = error.meta.code
      this.name = 'InstagramError'
  }
}
```

I am bad at English.

Sorry.

**Comment by gianfelipe93** [comment]
@Seungsoon, 

We refactored the way we was handling instagram error response, please pull the repository and try again.
